alstr/todo-to-issue-action

main.py
currently, this is making issues where the code block starts with ```golang}.
Note the extra } on the end. In my testing, this is because there is a missing newline. This PR adds one.
=> Fix line spacing error

syntax.json
Elixir comments are the same as python.
=> Support Elixir Programming Language

syntax.json
I have been poking around trying to determine how markdown should be supported but seems not to be. 
On my builds I see: "Could not check autoissue/nonsense.md for TODOs as this language is not yet supported by default."
I see that you download a large list of supported languages when trying to determine valid extensions, but it seems like without this addition to the syntax.json file, markdown isn't truly supported.
=> Adds markdown block support.

syntax.json
Technically block comments aren't supported in the base language, but the
```
\begin{comment} 
\end{comment}
```
is supported by a package
=> add Tex (and latex) support

README.md
Not sure if you are pedantic about linting, but I work in Markdown all day long, so it's a habit for me :)
Linter prefers preformatted code in code block with language definition.  The bonus is you get syntax highlighting.
Linter prohibits outer spaces in [] and () link blocks. No visual difference in rendered markdown.
=> Resolving syntax issues reported by MD linter

README.md, syntax.json
Reference to the documentation of comment syntax:
ABAP
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abencomment.htm
ABAP CDS
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abencds_general_syntax_rules.htm
Closes #85
=> Add support for ABAP and ABAP CDS languages

.gitignore, README.md, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
This PR aims to 
- Fix the issues observed in: https://github.com/alstr/todo-to-issue-action/issues/95
- Add test coverage for LaTeX line + block comments
I was able to identify this by adding a local change to swap `\begin` => `\\begin` and `\end` => `\\end` in the regex parts for LaTeX before parsing. However, not all tests pass after doing this (which appears to be due to other underlying issues with the tests). 
Also worth noting that the tests right now depend explicitly on the version of `syntax.json` which is on master of this repo, which makes it painful to test locally. I overrode that in the tests file to make them easier to work with in the future
=> Fix LaTeX bug + add tests

README.md, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
Adds support for [Crystal](https://crystal-lang.org/), a statically compiled language that is _very_ similar in syntax to Ruby.
=> feat: add Crystal

README.md
The user should permit the Project Actions in order to create the issue. Else it will print that Issue cannot be generated.
=> Update Troubleshooting in README.md file

syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
[R](https://en.wikipedia.org/wiki/R_(programming_language))
Comments are simply started with a `#`
I wasn't sure how to add a test...
=> Add language definition for R

syntax.json
Many packages (e.g. `todo`, `easy-todo`, `todonotes`) in LaTeX visually track TODOs in a document which makes them easy to see when editing; especially when sending to external editors. This commit adds support for these packages in LaTeX and creates GitHub issues just like you would have from a regular inline comment.
=> Adding `\todo` for LaTeX todos

syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
Hello alstr!
I added the GDScript programming language. I hope everything is alright with this. If there's anything wrong that I have to fix, please let me know, and I'll fix it asap.
=> added GDScript

action.yml, main.py
GitHub Enterprise Server uses a different API endpoint. This PR is aimed to support running this action on GHES by adding a new optional action input.
=> Add GITHUB_URL to support GHES

syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
Support is similar to Python, as it is a python dialect.  However, it does not support block comments.
See spec: https://github.com/bazelbuild/starlark/blob/master/spec.md
=> Add support for Starlark.

.gitignore, main.py, tests/test_closed.diff, tests/test_todo_parser.py
As mentioned in the title, you no longer need to include a space between a comment pattern and an identifier (See #155).
Additionally, I would like to mention that I have only updated some unit tests for the Julia programming language. If this is not sufficient, please leave a comment, and I will add more as needed.
=> Allows to have no spaces between a comment pattern and a TODO identifier

README.md, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
=> Add support for .cu files

README.md, main.py, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
If no extension is found for a file, it searches if said file exists within the filenames list of the language.
=> Extensionless files support + makefile language support added

README.md, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
Although line comments in Liquid require a wrapping liquid block in one way or another, I've included the line syntax `#` without consideration for the `{% %}` encapsulation due to the unlikelihood that `# TODO` will be used outside of a comment context.
Liquid input:
```liquid
{% # for i in (1..3) -%}
{{ i }}
{% # endfor %}
{%
###############################
###############################
%}
```
Output:
```
```
I'd be happy to make any changes that are suggested.
=> add support for Liquid files (.liquid)

main.py, tests/test_new.diff, tests/test_todo_parser.py
=> fix: check filename if no extensions match

main.py
This pull request addresses an issue with file handling in the main.py. The current test implementation uses `open()` without properly closing the file, which could potentially lead to resource leaks.
Change made:
Replace the direct `open()` call with a with statement to ensure proper file closure.
Improve code readability and adhere to Python best practices for file handling.
Before:
```python
f = open(path)
data = json.load(f)
...
```
After:
```python
with open(path) as f:
data = json.load(f)
```
Motivation:
While Python's garbage collector will eventually close the file when the file object is no longer referenced, it's generally considered good practice to explicitly close files or use a context manager to ensure they're closed promptly and also avoid resource leaks...
=> Improve file handling in `main.py`

.gitignore, README.md, syntax.json, tests/test_closed.diff, tests/test_new.diff, tests/test_todo_parser.py
**Language Name**: TOML
Tests based quite heavily on the YAML tests.
NOTE: I couldn't get the test suite to run for me (even the clean fork) and I tried a couple different versions of Python. Maybe worth adding to the documentation more detail around this.
=> Added TOML Support

.devcontainer/devcontainer.json, .github/workflows/ci.yml, Client.py, Dockerfile, GitHubClient.py, LocalClient.py, main.py, requirements-dev.txt, requirements.txt, tests/test_syntax.py
This contains some additional minor refactoring and adds another unittest file.
The following changes were made further isolate the VCS-specific code from that in `main`. 
- added abstract `Client` base class
- this also supports `mypy`-related changes, discussed below
- parse `MANUAL_COMMIT_REF` and `MANUAL_BASE_REF` environment variables within *`Client` so that diff URL can be VCS-specific
- for `LocalClient`, there is no URL, but parsing these variables allows it to call `git diff` with the proper arguments
- `Client:get_issue_url()` returns _just_ the URL string (when applicable), rather than prefixing it with "Issue URL: ". This allows the function to be used more generically.
In addition, per [this discussion](https://github.com/alstr/todo-to-issue-action/pull/217#issuecomment-24418 …
=> refactor and add tests

main.py, tests/test_comment_suffix_after_source_line.diff, tests/test_edit.diff, tests/test_new.diff, tests/test_new2.diff, tests/test_process_diff.py, tests/test_same_title_in_same_file.diff, tests/test_todo_parser.py
This PR addresses a number of bug fixes as well as adding a new test to demonstrate an existing bug (which this PR does not fix). 
Relevant issues:
- closes: #224, #225, #226
- related to: #216, #227
Issues #216, #224, and #225 all stem from the same root cause: the app doesn't properly handle a diff that introduces the same-titled TODO multiple times into the same file. This PR does NOT fix that root issue (a separate PR will do so though), but it DOES address the unintended side effect of introducing other, erroneous, lines into the source code. It will also prevent any future errors of this same class.
=> numerous bug fixes

Issue.py, TodoParser.py, tests/test_edit_py.diff, tests/test_new.diff, tests/test_new_py.diff, tests/test_process_diff.py, tests/test_todo_parser.py
This PR fixes several bugs related to case-sensitivity vs case-insensitive matching of the identifier. Unfortunately, as much as I tried to break it up into smaller PRs, the diff on TodoParser.py is pretty significant on this one.  For starters, I recommend viewing it by ignoring whitespace, as several blocks changed indentation.
I'll add inline comments to try to explain the major changes. But ultimately, as stated in the commit logs, these changes are about closing (and/or resolving the real root cause of) the following issues:
- #216
- #224 
- #225
- #230 
- #234
It also adds a test for, but does not resolve, #236
=> fix identifier case sensitivity bugs

TodoParser.py, tests/test_process_diff.py
track context of old and new lines separately to
get proper line numbers relative to old and
new version of a file
Closes GitHub #236
=> fix: get correct line numbering of old and new lines

Issue.py, TodoParser.py, main.py, tests/test_process_diff.py
If TODO comment is a suffix to a line of
(executable) source, don't repeat the source
content when inserting the issue URL. But be sure
to still keep the same alignment.
Closes #229
=> fix: don't include source with issue URL comment

TodoParser.py, main.py, tests/test_new.diff, tests/test_process_diff.py, tests/test_todo_parser.py
Provides a test for and the solution to GitHub
issue #242. Namely, an identifier which contains
regex characters (e.g. "[TODO]") is properly
handled by having the parser look for literal
"[" and "]" characters rather than treating those
characters as part of a regex pattern. The word
boundary regex pattern '\b' does NOT properly
handle this, so a slightly different pattern is
used to identify the boundary.
Closes #242
=> fix: handle identifier with regex characters

TodoParser.py, main.py
=> fix: handle different line endings

GitHubClient.py
`{}` were missing from an f-string causing an error in requests.
**Language Name**: Python
Fixes #253 
We appreciate your time and effort in improving this project!
=> Add {} to fix f-string

GitHubClient.py, README.md, action.yml
I made it so that you can supply a csv string of default labels to the action, which will be used to automatically apply labels to newly created issues, in addition to the individually tagged labels via the `labels:` comment.
I wasn't sure how to go about testing this, but I basically copied the implementation for Issue_template but configured it for the issue labels.
=> feat: adding default labels to issues

.github/workflows/ci.yml, tests/test_new.diff, tests/test_process_diff.py
When test_proces_diff processes `test_new.diff`, it creates the files that are referenced by the diff. If a file path contains a subdirectory, it fails to actually create the file, which in turn causes the test to fail. This PR cleans up `test_new.diff` such that no file is referenced within a subdirectory.
Updated number of expected passing tests to account for the additional tests which can run successfully now.
This is related to https://github.com/alstr/todo-to-issue-action/pull/266 and resolves the lingering issues that are referenced in comments there.
=> fix: remove subdirectory paths from test_new.diff

TodoParser.py
This small PR resolves the annoying regex library warnings starting Python3.11:
```python
TodoParser.py:366: DeprecationWarning: 'count' is passed as positional argument
```
=> fix: resolve regex library warnings
